// Mocks generated by Mockito 5.4.6 from annotations
// in digital_jeweller/test/features/master_admin/jeweller_management/domain/usecases/create_jeweller_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:digital_jeweller/features/master_admin/jeweller_management/domain/entities/jeweller.dart'
    as _i2;
import 'package:digital_jeweller/features/master_admin/jeweller_management/domain/repositories/jeweller_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeJeweller_0 extends _i1.SmartFake implements _i2.Jeweller {
  _FakeJeweller_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [JewellerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJewellerRepository extends _i1.Mock
    implements _i3.JewellerRepository {
  MockJewellerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Jeweller>> getJewellers() =>
      (super.noSuchMethod(
            Invocation.method(#getJewellers, []),
            returnValue: _i4.Future<List<_i2.Jeweller>>.value(<_i2.Jeweller>[]),
          )
          as _i4.Future<List<_i2.Jeweller>>);

  @override
  _i4.Future<_i2.Jeweller> createJeweller(_i2.Jeweller? jeweller) =>
      (super.noSuchMethod(
            Invocation.method(#createJeweller, [jeweller]),
            returnValue: _i4.Future<_i2.Jeweller>.value(
              _FakeJeweller_0(
                this,
                Invocation.method(#createJeweller, [jeweller]),
              ),
            ),
          )
          as _i4.Future<_i2.Jeweller>);

  @override
  _i4.Future<String> deleteJeweller(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteJeweller, [id]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#deleteJeweller, [id]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i2.Jeweller> toggleJewellerStatus(String? id, bool? isActive) =>
      (super.noSuchMethod(
            Invocation.method(#toggleJewellerStatus, [id, isActive]),
            returnValue: _i4.Future<_i2.Jeweller>.value(
              _FakeJeweller_0(
                this,
                Invocation.method(#toggleJewellerStatus, [id, isActive]),
              ),
            ),
          )
          as _i4.Future<_i2.Jeweller>);
}
